name: beedi_college
description: "BEEDI College App एक modern digital platform है जो students के लिए learning और practice को आसान और smart बनाता है। यह app खासतौर पर KYP (Kushal Yuva Program) और अन्य computer courses के छात्रों को ध्यान में रखकर बनाया गया है।"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.9
  intl: ^0.20.2
  firebase_core: ^4.7.0
  flutter_launcher_icons: ^0.14.4
  path_provider: ^2.1.5
  shared_preferences: ^2.5.5
  flutter_staggered_animations: ^1.1.1
  provider: ^6.1.5+1
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.3.0
  firebase_storage: ^13.3.0
  google_sign_in: ^7.2.0
  image_picker: ^1.2.1
  file_picker: ^11.0.2
  flutter_local_notifications: ^21.0.0
  url_launcher: ^6.3.2
  pdf: ^3.12.0
  printing: ^5.14.3
  fl_chart: ^1.2.0
  google_fonts: ^8.0.2
  shimmer: ^3.0.0
  material_symbols_icons: ^4.2928.1
  excel: ^4.0.6
  open_file: ^3.5.11
  connectivity_plus: ^7.1.1
  permission_handler: ^12.0.1
  share_plus: ^12.0.2
  flutter_markdown: ^0.7.7+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Logoes/Logo.png
    - assets/Students/studentname.json
    - assets/Documents/Question/BS_CIT.json
    - assets/Documents/Question/BS_CLS.json
    - assets/Documents/Question/BS_CSS.json

flutter_icons:
  android: true
  ios: true
  image_path: "assets/Logoes/Logo.png"