// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuChIECMvEjKUtz8iYforwL5C9JVURYYo',
    appId: '1:836903145620:web:64beb2762351df82a32481',
    messagingSenderId: '836903145620',
    projectId: 'beedicollegevaishali',
    authDomain: 'beedicollegevaishali.firebaseapp.com',
    storageBucket: 'beedicollegevaishali.firebasestorage.app',
    measurementId: 'G-33GND8R8NX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlYTycKQykpb_1OlzrWXMWe4UgqPeuEC4',
    appId: '1:836903145620:android:7b9bb239919aabdba32481',
    messagingSenderId: '836903145620',
    projectId: 'beedicollegevaishali',
    storageBucket: 'beedicollegevaishali.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG3VWUdG5ozq3warYRybjzgNaeRxb_ewY',
    appId: '1:836903145620:ios:6b5a9de4024979eaa32481',
    messagingSenderId: '836903145620',
    projectId: 'beedicollegevaishali',
    storageBucket: 'beedicollegevaishali.firebasestorage.app',
    iosBundleId: 'com.example.beediCollege',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG3VWUdG5ozq3warYRybjzgNaeRxb_ewY',
    appId: '1:836903145620:ios:6b5a9de4024979eaa32481',
    messagingSenderId: '836903145620',
    projectId: 'beedicollegevaishali',
    storageBucket: 'beedicollegevaishali.firebasestorage.app',
    iosBundleId: 'com.example.beediCollege',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuChIECMvEjKUtz8iYforwL5C9JVURYYo',
    appId: '1:836903145620:web:a9785a9da62e934da32481',
    messagingSenderId: '836903145620',
    projectId: 'beedicollegevaishali',
    authDomain: 'beedicollegevaishali.firebaseapp.com',
    storageBucket: 'beedicollegevaishali.firebasestorage.app',
    measurementId: 'G-L5X6N4THBD',
  );
}
